### PR TITLE
Feature/update

### PR DESCRIPTION
**Pull request by pierrechoffe**
First 2 commits: delete properties and classes, due to the new modeling of Casting
reassign property id (U1 etc.) to a new property

### CODE REVIEW

**Comment by rtroncy** [comment]
This looks good for me. @pasqLisena, can you confirm? What are the consequences for [MARC2RDF](https://github.com/DOREMUS-ANR/marc2rdf/)?

**Comment by pierrechoffe** [comment]
@rtroncy remember there are some more to be committed tonight :)

**Comment by pasqLisena** [comment]
It looks good also for me. Let's wait this night commits 😄 

Marc2rdf has a script for automatically updating the ontology. So we can realize (and update) each difference without difficulty.

**Comment by rtroncy** [comment]
I'm merging now, since if you make another PR, you will have to re-base or you will be in an inconsistent state

**Comment by pierrechoffe** [comment]
just downloaded the new version, going to my kyudo, will work on it tonight :)

**Comment by delahousse** [comment]
Bonjour,

Ci joint le tableau des classes, propriétés et classes/propriétés sur la
base de la dernière version de l'ontologie.

Bonne journée
Jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data
https://fr.linkedin.com/in/jeandelahousse
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

2016-09-12 16:18 GMT+01:00 Pierre Choffé <notifications@github.com>:

**Comment by rtroncy** [comment]
@delahousse Il n'y avait pas de fichiers attachés, mais les commentaires d'un Pull Request sur github ne sont sans doute pas le meilleur lieu pour cela ;-)

**Comment by delahousse** [comment]
ok je n'avais pas remarqué
jean

Jean Delahousse

Independent Consultant
Semantic technologies, Linked Open Data
https://fr.linkedin.com/in/jeandelahousse
delahousse.jean@gmail.com  <delahousse.jean@gmail.com>
mob +33 6 01 22 48 55
skype jean.delahousse

Le 12 septembre 2016 à 22:48, Raphael Troncy <notifications@github.com> a
écrit :

**Pull request merged**
