### PR TITLE
Feature/update2

### PR DESCRIPTION
**Pull request by pierrechoffe**
Now up to date with the most stable classes and properties.
Note : I used Protégé 5.0 for desktop which changed the layout (see commit nr. 1)

### CODE REVIEW

**Comment by rtroncy** [comment]
I have not reviewed the long list of new properties which have been added. I let @pasqLisena to say if this is ok. For me, this is good, we can always nitpick on the exact property name / labels later on as soon as we update MARC2RDF.

**Comment by pasqLisena** [comment]
I have some doubts: 😄 
1. why `mus:U24_has_successor_in_order` and `mus:U25_has_successor_in_time` are subclass of `ecrm:P130_shows_features_of`?
2. what is the difference between `efrbroo:F31_Performance` and our `mus:M43_Performed_Expression`?

**Comment by pierrechoffe** [comment]
@pasqLisena very good questions! :smile:

1. I tried to stick to the FRBRoo logic of R1_is_logical_successor_of , which is also a subproperty of P130.
2. M43_Performed _Expression is an Expression so I assume your question is "what is the different between M42_Performed_Expression_Creation and F31_Performance" ? Yes, M42 is a performance as well, but a special one : while an F31 Performance is "just" a performance, which does not create anything, this M42 creates an Expression (which realises a Work, since we stick to the FRBRoo logic).
Why create M42 and M43? because not all performances perform a preexisting Work (think of improvisation, but also of some traditional music) and when they do they may perform it in a such a way that you cannot say they "just" performed the Work (a typical case, though not unique, is jazz performance: *My Favorite Things* by John Coltrane is not "just" a performance of the original from *The Sound of Music*.
The Performed_Expression allows for describing this new musical piece. More generally, we have a handy way of describing "performed music" on top of the usual "notated music" (the F22).
There are other advantages in creating this performed music expression beside the notated music expression but this is the not place to talk about it.

**Comment by rtroncy** [comment]
1) I indeed see that ```frbroo:R1``` is a subPropertyOf ```ecrm:P130``` and I understand the analogy you wanted to replicate. ```frbroo:R1``` is between F1_Work ... what is the domain (and range) of the ```mus:24``` and ```mus:25``` properties?

2) No, @pasqLisena original question was a true question, not your reformulation, and between, what is a ```F31_Performance``` (since ultimately, everything is an expression)? ```M42``` is not the performance ... it is an event that creates the performance, no? You're using terms that sometimes describe the event and sometime the result which causes the confusion.

I failed to see what are the fundamental differences between a ```mus:M42``` and a ```mus:M43``` and in particular, why do you need to distinguish them by a type (as opposed to the rest of the graph)?

**Comment by pasqLisena** [comment]
Thanks @pierrechoffe.

1. Ok, but `ecrm:P130_shows_features_of` speaks about [_similarity_](http://erlangen-crm.org/docs/ecrm/111122/objectproperties/P130showsfeaturesof___1040905516.html). We have not this concept in chronological/numerical succession.

2. So, briefly, we will represent a performance:
 - with F31_Performance when it don't generate something that we can consider an Expression, but only a manifestation;
 - with M42+M43 when we can consider it a new Expression (and so attaching title etc.)
I understood well?

3. I added question number 3 editing previous comment, maybe you have not seen it 😄

**Comment by pierrechoffe** [comment]
@rtroncy 
1) the domain and range of P130 are ecrm:E70_Thing (which is very broad...). The domain and range of R1 are frbroo:F1_Work (much narrower). The domain and range of mus:U24 and mus:U25 are mus:M24_Track (an Expression)

@pasqLisena 
1) I understand your point, yet it would apply also to the frbroo:R1 property : "logical successor" does not imply any similarity. Do you have any suggestion?

@rtroncy @pasqLisena 
2) I think there is a big misunderstanding : frbroo:F31_Performance is not an Expression, it is an Event. This Event does not create anything, no Expression, no Manifestation, no nothing (btw there is no event creating a Manifestation Type).
So far, we were kind of reproducing the usual FRBRoo model where you have an Expression (F22) being performed (via F25 etc.) by an event called F31_Performance. In FRBRoo, an F31_Performance does not create any Expression, so basically it just says that this song was performed. Period. But this was a problem for us, since we have cases where a musician may perform something *that did not exist before*. In this case, we could not describe this something. Furthermore, this something that did not exist before now exists. It may have been filmed or recorded, it may only exist in our memory, but it does exist.
"While the FRBRoo model does not say that a performance creates an Expression, it does not prohibit it either" (dixit P. Le Boeuf).
Therefore we created this concept of a "performance that creates an Expression" and we called this event "M42_Performed_Expression_Creation". The result of this event is an Expression, called "M43 Performed Expression".
This is useful not only for improvisation or for traditional music but also for classical music.
An example: JS Bach's Concerto for hapsichord and orchestra BWV 1060 being played (and recorded on CD) on violin, oboe and orchestra with the same identifier BWV 1060. If you create a new Work, this is wrong (because you will have 2 different pieces with the same identifier), if you say (as we did before) that the album incorporates (via F31 and F25 etc.) the piece for harpsichord and orchestra, this is wrong too (or at least not explicit at all), because this is clearly for violin, oboe and orchestra. But with this solution we have 2 distinct Expressions and we can create properties between them to make their relation explicit.
_____________
Now Pasquale, to answer your 2nd question, we will use M42 each time, even when we have nothing special to say about M43. So, no more F31 (or maybe just as a node, with F31 p9 consists of various M42). The standard Performance now is M42 and all performances create a Performed Expression.

@pasqLisena 
3) you are right, I had to "reconstruct" the tree for frbroo:F38_Character, which is a subclass of ecrm:E28_Conceptual_Object. Clearly this should be in the FRBRoo ontology. Same thing with frbroo:F50

I will ask the people at erlangen.

**Comment by rtroncy** [comment]
@pierrechoffe So, you want to define two new properties (```mus:U24``` and ```mus:U25```) for representing some orders between Tracks? Can you give a concrete example why we should have both in the first place? Next, why don't you use the built-in ```rdf:List``` which is aimed to represent an ordered list of resources?

Thanks for clarifying what is a ```efrbroo:F31_Performance```. I have always said that nothing prevents us to describe that a ```efrbroo:F31_Performance``` can create an expression, therefore, I don't understand why do you want to create a specific M42 class. Is it to distinguish performance that creates expressions or not? Besides the fact that this is really argue-able, this is not necessary at all, the whole graph enables already to make this distinction. So what is the purpose of M42?

Similarly, why do you want to create a M43, if this is an expression? What is the fundamental distinction of a M43 in terms of being an expression? Are there different type of expressions (fundamentally)? If this is just to indicate that it results from a performance, well, again the graph says it already, no need to sub-type.

**Comment by rtroncy** [comment]
Merging now the PR. We will keep discussing the modeling questions above in new issues that need to be created

**Comment by pasqLisena** [comment]
Issues created

**Pull request merged**
